import { DecimalPipe } from '@angular/common';
import { Component, DestroyRef, inject, OnInit, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormArray, FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { merge } from 'rxjs';
import { Branch } from '../../../../core/api/models/branch.models';
import { Currency } from '../../../../core/api/models/currency.models';
import { ProductLookup } from '../../../../core/api/models/product.models';
import { ItemUnitLookup, StockLineDetail, isStockDocPosted } from '../../../../core/api/models/stock-shared.models';
import { SaveStockTransferRequest } from '../../../../core/api/models/stock-transfer.models';
import { Store } from '../../../../core/api/models/store.models';
import { extractApiErrorMessage } from '../../../../core/api/utils/api-response.util';
import { TranslatePipe } from '../../../../core/pipes/translate.pipe';
import { BranchesService } from '../../../../core/services/branches.service';
import { CurrenciesService } from '../../../../core/services/currencies.service';
import { LanguageService } from '../../../../core/services/language.service';
import { ProductsService } from '../../../../core/services/products.service';
import { StockTransfersService } from '../../../../core/services/stock-transfers.service';
import { StoresService } from '../../../../core/services/stores.service';
type Line = FormGroup<{ itemId: FormControl<number | null>; unitId: FormControl<number | null>; quantity: FormControl<number>; price: FormControl<number>; total: FormControl<number>; barcode: FormControl<string>; batchNumber: FormControl<string>; expiryDate: FormControl<string>; availableQty: FormControl<number | null> }>;
@Component({ selector: 'app-stock-transfer-form', imports: [RouterLink, ReactiveFormsModule, TranslatePipe, DecimalPipe], templateUrl: './stock-transfer-form.component.html', styleUrl: './stock-transfer-form.component.scss' })
export class StockTransferFormComponent implements OnInit {
  private route=inject(ActivatedRoute); private router=inject(Router); private destroyRef=inject(DestroyRef); private service=inject(StockTransfersService); private branchesService=inject(BranchesService); private storesService=inject(StoresService); private productsService=inject(ProductsService); private currenciesService=inject(CurrenciesService); private language=inject(LanguageService);
  loading=signal(false); saving=signal(false); isEditMode=signal(false); isReadOnly=signal(false); transferId=signal<number|null>(null); errorMessage=signal(''); totalAmount=signal(0); branches=signal<Branch[]>([]); fromStores=signal<Store[]>([]); toStores=signal<Store[]>([]); products=signal<ProductLookup[]>([]); currencies=signal<Currency[]>([]); lineUnits=signal<ItemUnitLookup[][]>([]);
  form=new FormGroup({transferNumber:new FormControl({value:'',disabled:true},{nonNullable:true}),transferDate:new FormControl(this.today(),{nonNullable:true,validators:Validators.required}),fromBranchId:new FormControl<number|null>(null,Validators.required),fromStoreId:new FormControl<number|null>(null,Validators.required),toBranchId:new FormControl<number|null>(null,Validators.required),toStoreId:new FormControl<number|null>(null,Validators.required),currencyId:new FormControl<number|null>(null),exchangeRate:new FormControl(1,{nonNullable:true}),reference:new FormControl('',{nonNullable:true}),responsibleName:new FormControl('',{nonNullable:true}),notes:new FormControl('',{nonNullable:true}),details:new FormArray<Line>([])});
  get details(){return this.form.controls.details;} today(){return new Date().toISOString().slice(0,10);}
  ngOnInit(){this.branchesService.getAll().subscribe({next:x=>this.branches.set(x)});this.productsService.getAll().subscribe({next:x=>this.products.set(x)});this.currenciesService.getAll().subscribe({next:x=>this.currencies.set(x)});this.form.controls.fromBranchId.valueChanges.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(x=>this.branch(x,'from'));this.form.controls.toBranchId.valueChanges.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(x=>this.branch(x,'to'));const id=Number(this.route.snapshot.paramMap.get('id'));if(id){this.isEditMode.set(true);this.transferId.set(id);this.load(id);}else this.addLine();}
  branch(id:number|null,side:'from'|'to'){if(this.isReadOnly())return;const store=side==='from'?this.form.controls.fromStoreId:this.form.controls.toStoreId;store.setValue(null);if(!id)return;(side==='from'?this.fromStores:this.toStores).set([]);this.storesService.getByBranch(id).subscribe({next:x=>(side==='from'?this.fromStores:this.toStores).set(x)});if(side==='from'&&!this.isEditMode())this.service.getNextNumber(id).subscribe({next:x=>this.form.controls.transferNumber.setValue(x.voucherNumber??'')});}
  load(id:number){this.loading.set(true);this.service.getById(id).subscribe({next:d=>{this.isReadOnly.set(isStockDocPosted(d.status, d.datePosted));this.form.patchValue({transferNumber:d.transferNumber??'',transferDate:d.transferDate?.slice(0,10)??this.today(),fromBranchId:d.fromBranchId,fromStoreId:d.fromStoreId,toBranchId:d.toBranchId,toStoreId:d.toStoreId,currencyId:d.currencyId??null,exchangeRate:d.exchangeRate??1,reference:d.reference??'',responsibleName:d.responsibleName??'',notes:d.notes??''});this.loadStores(d.fromBranchId,'from',d.fromStoreId);this.loadStores(d.toBranchId,'to',d.toStoreId);this.rebuild(d.details??[]);if(this.isReadOnly())this.form.disable();this.loading.set(false);},error:e=>{this.loading.set(false);this.errorMessage.set(extractApiErrorMessage(e,this.language.translate('stockTransfers.loadError')));}});}
  loadStores(id:number,side:'from'|'to',selected?:number){this.storesService.getByBranch(id).subscribe({next:x=>{(side==='from'?this.fromStores:this.toStores).set(x);if(selected!=null)(side==='from'?this.form.controls.fromStoreId:this.form.controls.toStoreId).setValue(selected);}});}
  line():Line{return new FormGroup({itemId:new FormControl<number|null>(null,Validators.required),unitId:new FormControl<number|null>(null,Validators.required),quantity:new FormControl(1,{nonNullable:true,validators:[Validators.required,Validators.min(.0001)]}),price:new FormControl(0,{nonNullable:true,validators:[Validators.required,Validators.min(0)]}),total:new FormControl(0,{nonNullable:true}),barcode:new FormControl('',{nonNullable:true}),batchNumber:new FormControl('',{nonNullable:true}),expiryDate:new FormControl('',{nonNullable:true}),availableQty:new FormControl<number|null>(null)});}
  addLine(){const l=this.line();this.details.push(l);this.lineUnits.update(x=>[...x,[]]);this.bind(l);} rebuild(ds:StockLineDetail[]){this.details.clear();this.lineUnits.set([]);ds.forEach(d=>{const l=this.line();l.patchValue({itemId:d.itemId,unitId:d.unitId,quantity:d.quantity,price:d.price,total:d.total,barcode:d.barcode??'',batchNumber:d.batchNumber??'',expiryDate:d.expiryDate?.slice(0,10)??'',availableQty:d.availableQty??null});this.details.push(l);this.lineUnits.update(x=>[...x,[]]);this.bind(l);this.units(this.details.length-1,d.itemId,d.unitId);});if(!ds.length)this.addLine();this.retotal();}
  bind(l:Line){merge(l.controls.quantity.valueChanges,l.controls.price.valueChanges).pipe(takeUntilDestroyed(this.destroyRef)).subscribe(()=>this.calc(l));l.controls.itemId.valueChanges.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(id=>{const i=this.details.controls.indexOf(l);if(id)this.units(i,id);});merge(l.controls.unitId.valueChanges,l.controls.batchNumber.valueChanges,l.controls.expiryDate.valueChanges).pipe(takeUntilDestroyed(this.destroyRef)).subscribe(()=>this.available(l));}
  units(i:number,id:number,selected?:number){this.service.getItemUnits(id).subscribe({next:us=>{this.lineUnits.update(a=>{const n=[...a];n[i]=us;return n;});const l=this.details.at(i);if(l)l.controls.unitId.setValue(us.some(x=>x.unitId===selected)?selected!:(us.find(x=>x.isBaseUnit)??us[0])?.unitId??null);}});} unitsFor(i:number){return this.lineUnits()[i]??[];}   calc(l:Line){const qty=Number(l.controls.quantity.value)||0;const price=Number(l.controls.price.value)||0;l.controls.total.setValue(Number((qty*price).toFixed(4)),{emitEvent:false});this.retotal();} retotal(){this.totalAmount.set(Number(this.details.controls.reduce((s,l)=>s+(Number(l.controls.total.value)||0),0).toFixed(4)));}
  lookup(l:Line,e:Event){e.preventDefault();const b=l.controls.barcode.value.trim();if(b)this.service.lookupBarcode(b).subscribe({next:x=>{l.patchValue({itemId:x.itemId,unitId:x.unitId,price:x.currentCost??0});this.calc(l);}});} available(l:Line){const itemId=l.controls.itemId.value,unitId=l.controls.unitId.value,branchId=this.form.controls.fromBranchId.value,storeId=this.form.controls.fromStoreId.value;if(itemId&&unitId&&branchId&&storeId)this.service.getAvailableQty({itemId,unitId,branchId,storeId,batchNo:l.controls.batchNumber.value||undefined,expiryDate:l.controls.expiryDate.value||undefined}).subscribe({next:x=>l.controls.availableQty.setValue(x.qtyInUnit??x.baseQty??null)});}
  removeLine(i:number){this.details.removeAt(i);this.lineUnits.update(x=>x.filter((_,j)=>j!==i));this.retotal();} productLabel(p:ProductLookup){return[p.productName,p.proCode].filter(Boolean).join(' - ')||String(p.productId);} branchLabel(b:Branch){return b.branchName||String(b.branchId);} currencyLabel(c:Currency){return c.currencyName||c.currencyShorcut||String(c.id);}
  save(){
    if(this.isReadOnly())return;
    this.details.controls.forEach(l=>this.calc(l));
    this.form.markAllAsTouched();
    this.errorMessage.set('');
    const missing:string[]=[];
    if(this.form.controls.fromBranchId.invalid)missing.push(this.language.translate('stockTransfers.required.fromBranch'));
    if(this.form.controls.fromStoreId.invalid)missing.push(this.language.translate('stockTransfers.required.fromStore'));
    if(this.form.controls.toBranchId.invalid)missing.push(this.language.translate('stockTransfers.required.toBranch'));
    if(this.form.controls.toStoreId.invalid)missing.push(this.language.translate('stockTransfers.required.toStore'));
    if(!this.details.length||this.details.invalid)missing.push(this.language.translate('stockTransfers.required.details'));
    if(missing.length||this.form.invalid){this.errorMessage.set(missing.join(' — ')||this.language.translate('stockTransfers.saveError'));return;}
    const r=this.form.getRawValue();
    if(r.fromBranchId==null||r.fromStoreId==null||r.toBranchId==null||r.toStoreId==null)return;
    this.saving.set(true);
    const p:SaveStockTransferRequest={transferId:this.transferId()??undefined,transferNumber:r.transferNumber,transferDate:new Date(r.transferDate).toISOString(),fromBranchId:r.fromBranchId,fromStoreId:r.fromStoreId,toBranchId:r.toBranchId,toStoreId:r.toStoreId,currencyId:r.currencyId,exchangeRate:Number(r.exchangeRate)||1,reference:r.reference||null,responsibleName:r.responsibleName||null,notes:r.notes||null,totalAmount:this.totalAmount(),details:r.details.map(x=>({itemId:x.itemId!,unitId:x.unitId!,quantity:Number(x.quantity),price:Number(x.price),total:Number(x.total),barcode:x.barcode||null,batchNumber:x.batchNumber||null,expiryDate:x.expiryDate?new Date(x.expiryDate).toISOString():null}))};
    this.service.save(p).subscribe({next:x=>{this.saving.set(false);void this.router.navigate(x.transferId?['/demo1/inventory/stock-transfers',x.transferId]:['/demo1/inventory/stock-transfers'],{state:{successMessage:this.language.translate('stockTransfers.saveSuccess')}});},error:e=>{this.saving.set(false);this.errorMessage.set(extractApiErrorMessage(e,this.language.translate('stockTransfers.saveError')));}});
  }
}
