import { Routes } from '@angular/router';
import { authGuard, guestGuard } from './core/api/guards/auth.guard';
import { Demo1Component } from './layouts/demo1/demo1.component';
import { SignInComponent } from './pages/auth/sign-in/sign-in.component';
import { IndexComponent as Demo1IndexComponent } from './pages/demo1/index/index.component';
import { PermissionsPageComponent } from './pages/settings/permissions/permissions-page/permissions-page.component';
import { RolesListComponent } from './pages/settings/roles/roles-list/roles-list.component';
import { RoleFormComponent } from './pages/settings/roles/role-form/role-form.component';
import { BranchesListComponent } from './pages/settings/branches/branches-list/branches-list.component';
import { BranchFormComponent } from './pages/settings/branches/branch-form/branch-form.component';
import { CompaniesListComponent } from './pages/settings/companies/companies-list/companies-list.component';
import { CompanyFormComponent } from './pages/settings/companies/company-form/company-form.component';
import { CurrenciesListComponent } from './pages/settings/currencies/currencies-list/currencies-list.component';
import { CurrencyFormComponent } from './pages/settings/currencies/currency-form/currency-form.component';
import { SystemLogFormComponent } from './pages/settings/system-logs/system-log-form/system-log-form.component';
import { SystemLogsListComponent } from './pages/settings/system-logs/system-logs-list/system-logs-list.component';
import { UserFormComponent } from './pages/settings/users/user-form/user-form.component';
import { UsersListComponent } from './pages/settings/users/users-list/users-list.component';
import { CustomerGroupFormComponent } from './pages/sales/customer-groups/customer-group-form/customer-group-form.component';
import { CustomerGroupsListComponent } from './pages/sales/customer-groups/customer-groups-list/customer-groups-list.component';
import { CustomerFormComponent } from './pages/sales/customers/customer-form/customer-form.component';
import { CustomersListComponent } from './pages/sales/customers/customers-list/customers-list.component';
import { SalesmanFormComponent } from './pages/sales/salesmen/salesman-form/salesman-form.component';
import { SalesmenListComponent } from './pages/sales/salesmen/salesmen-list/salesmen-list.component';
import { SalesInvoiceFormComponent } from './pages/sales/sales-invoices/sales-invoice-form/sales-invoice-form.component';
import { SalesInvoicesListComponent } from './pages/sales/sales-invoices/sales-invoices-list/sales-invoices-list.component';
import { ProductGroupFormComponent } from './pages/products/product-groups/product-group-form/product-group-form.component';
import { ProductGroupsListComponent } from './pages/products/product-groups/product-groups-list/product-groups-list.component';
import { ProductFormComponent } from './pages/products/items/product-form/product-form.component';
import { ProductsListComponent } from './pages/products/items/products-list/products-list.component';
import { UnitFormComponent } from './pages/products/units/unit-form/unit-form.component';
import { UnitsListComponent } from './pages/products/units/units-list/units-list.component';
import { AccountGroupFormComponent } from './pages/accounting/account-groups/account-group-form/account-group-form.component';
import { AccountGroupsListComponent } from './pages/accounting/account-groups/account-groups-list/account-groups-list.component';
import { AccountingPeriodFormComponent } from './pages/accounting/periods/accounting-period-form/accounting-period-form.component';
import { AccountingPeriodsListComponent } from './pages/accounting/periods/accounting-periods-list/accounting-periods-list.component';
import { FiscalYearFormComponent } from './pages/accounting/fiscal-years/fiscal-year-form/fiscal-year-form.component';
import { FiscalYearsListComponent } from './pages/accounting/fiscal-years/fiscal-years-list/fiscal-years-list.component';
import { AccountFormComponent } from './pages/accounting/accounts/account-form/account-form.component';
import { AccountsTreeComponent } from './pages/accounting/accounts/accounts-tree/accounts-tree.component';
import { CostCenterFormComponent } from './pages/accounting/cost-centers/cost-center-form/cost-center-form.component';
import { CostCentersListComponent } from './pages/accounting/cost-centers/cost-centers-list/cost-centers-list.component';
import { TaxSetupFormComponent } from './pages/accounting/tax-setups/tax-setup-form/tax-setup-form.component';
import { TaxSetupsListComponent } from './pages/accounting/tax-setups/tax-setups-list/tax-setups-list.component';
import { OpeningBalanceFormComponent } from './pages/accounting/opening-balances/opening-balance-form/opening-balance-form.component';
import { OpeningBalancesListComponent } from './pages/accounting/opening-balances/opening-balances-list/opening-balances-list.component';
import { JournalEntryFormComponent } from './pages/accounting/journal-entries/journal-entry-form/journal-entry-form.component';
import { JournalEntriesListComponent } from './pages/accounting/journal-entries/journal-entries-list/journal-entries-list.component';
import { PaymentVoucherFormComponent } from './pages/accounting/payment-vouchers/payment-voucher-form/payment-voucher-form.component';
import { PaymentVouchersListComponent } from './pages/accounting/payment-vouchers/payment-vouchers-list/payment-vouchers-list.component';
import { ReceiptVoucherFormComponent } from './pages/accounting/receipt-vouchers/receipt-voucher-form/receipt-voucher-form.component';
import { ReceiptVouchersListComponent } from './pages/accounting/receipt-vouchers/receipt-vouchers-list/receipt-vouchers-list.component';
import { GeneralLedgerComponent } from './pages/accounting/reports/general-ledger/general-ledger.component';
import { TrialBalanceComponent } from './pages/accounting/reports/trial-balance/trial-balance.component';
import { BanksListComponent } from './pages/banks/banks/banks-list/banks-list.component';
import { BankFormComponent } from './pages/banks/banks/bank-form/bank-form.component';
import { BankAccountsListComponent } from './pages/banks/accounts/bank-accounts-list/bank-accounts-list.component';
import { BankAccountFormComponent } from './pages/banks/accounts/bank-account-form/bank-account-form.component';
import { CheckBooksListComponent } from './pages/banks/check-books/check-books-list/check-books-list.component';
import { CheckBookFormComponent } from './pages/banks/check-books/check-book-form/check-book-form.component';
import { IssuedChecksListComponent } from './pages/accounting/issued-checks/issued-checks-list/issued-checks-list.component';
import { IssuedCheckFormComponent } from './pages/accounting/issued-checks/issued-check-form/issued-check-form.component';

export const routes: Routes = [
  { path: '', pathMatch: 'full', redirectTo: 'auth/sign-in' },
  { path: 'auth/sign-in', component: SignInComponent, canActivate: [guestGuard] },
  {
    path: 'demo1',
    component: Demo1Component,
    canActivate: [authGuard],
    children: [
      { path: '', component: Demo1IndexComponent },
      { path: 'settings/users', component: UsersListComponent },
      { path: 'settings/users/new', component: UserFormComponent },
      { path: 'settings/users/:id/edit', component: UserFormComponent },
      { path: 'settings/roles', component: RolesListComponent },
      { path: 'settings/roles/new', component: RoleFormComponent },
      { path: 'settings/roles/:id/edit', component: RoleFormComponent },
      { path: 'settings/permissions', component: PermissionsPageComponent },
      { path: 'settings/companies', component: CompaniesListComponent },
      { path: 'settings/companies/new', component: CompanyFormComponent },
      { path: 'settings/companies/:id/edit', component: CompanyFormComponent },
      { path: 'settings/branches', component: BranchesListComponent },
      { path: 'settings/branches/new', component: BranchFormComponent },
      { path: 'settings/branches/:id/edit', component: BranchFormComponent },
      { path: 'settings/currencies', component: CurrenciesListComponent },
      { path: 'settings/currencies/new', component: CurrencyFormComponent },
      { path: 'settings/currencies/:id/edit', component: CurrencyFormComponent },
      { path: 'settings/system-logs', component: SystemLogsListComponent },
      { path: 'settings/system-logs/new', component: SystemLogFormComponent },
      { path: 'sales/customer-groups', component: CustomerGroupsListComponent },
      { path: 'sales/customer-groups/new', component: CustomerGroupFormComponent },
      { path: 'sales/customer-groups/:id/edit', component: CustomerGroupFormComponent },
      { path: 'sales/customers', component: CustomersListComponent },
      { path: 'sales/customers/new', component: CustomerFormComponent },
      { path: 'sales/customers/:id/edit', component: CustomerFormComponent },
      { path: 'sales/salesmen', component: SalesmenListComponent },
      { path: 'sales/salesmen/new', component: SalesmanFormComponent },
      { path: 'sales/salesmen/:id/edit', component: SalesmanFormComponent },
      { path: 'sales/sales-invoices', component: SalesInvoicesListComponent },
      { path: 'sales/sales-invoices/new', component: SalesInvoiceFormComponent },
      { path: 'sales/sales-invoices/:id', component: SalesInvoiceFormComponent },
      { path: 'products/groups', component: ProductGroupsListComponent },
      { path: 'products/groups/new', component: ProductGroupFormComponent },
      { path: 'products/groups/:id/edit', component: ProductGroupFormComponent },
      { path: 'products/items', component: ProductsListComponent },
      { path: 'products/items/new', component: ProductFormComponent },
      { path: 'products/items/:id/edit', component: ProductFormComponent },
      { path: 'products/units', component: UnitsListComponent },
      { path: 'products/units/new', component: UnitFormComponent },
      { path: 'products/units/:id/edit', component: UnitFormComponent },
      { path: 'accounting/account-groups', component: AccountGroupsListComponent },
      { path: 'accounting/account-groups/new', component: AccountGroupFormComponent },
      { path: 'accounting/account-groups/:id/edit', component: AccountGroupFormComponent },
      { path: 'accounting/periods', component: AccountingPeriodsListComponent },
      { path: 'accounting/periods/new', component: AccountingPeriodFormComponent },
      { path: 'accounting/periods/:id/edit', component: AccountingPeriodFormComponent },
      { path: 'accounting/fiscal-years', component: FiscalYearsListComponent },
      { path: 'accounting/fiscal-years/new', component: FiscalYearFormComponent },
      { path: 'accounting/fiscal-years/:id/edit', component: FiscalYearFormComponent },
      { path: 'accounting/accounts', component: AccountsTreeComponent },
      { path: 'accounting/accounts/new', component: AccountFormComponent },
      { path: 'accounting/accounts/:id/edit', component: AccountFormComponent },
      { path: 'accounting/cost-centers', component: CostCentersListComponent },
      { path: 'accounting/cost-centers/new', component: CostCenterFormComponent },
      { path: 'accounting/cost-centers/:id/edit', component: CostCenterFormComponent },
      { path: 'accounting/tax-setups', component: TaxSetupsListComponent },
      { path: 'accounting/tax-setups/new', component: TaxSetupFormComponent },
      { path: 'accounting/tax-setups/:id/edit', component: TaxSetupFormComponent },
      { path: 'accounting/opening-balances', component: OpeningBalancesListComponent },
      { path: 'accounting/opening-balances/new', component: OpeningBalanceFormComponent },
      { path: 'accounting/opening-balances/:id/edit', component: OpeningBalanceFormComponent },
      { path: 'accounting/journal-entries', component: JournalEntriesListComponent },
      { path: 'accounting/journal-entries/new', component: JournalEntryFormComponent },
      { path: 'accounting/journal-entries/:id/edit', component: JournalEntryFormComponent },
      { path: 'accounting/payment-vouchers', component: PaymentVouchersListComponent },
      { path: 'accounting/payment-vouchers/new', component: PaymentVoucherFormComponent },
      { path: 'accounting/payment-vouchers/:id/edit', component: PaymentVoucherFormComponent },
      { path: 'accounting/receipt-vouchers', component: ReceiptVouchersListComponent },
      { path: 'accounting/receipt-vouchers/new', component: ReceiptVoucherFormComponent },
      { path: 'accounting/receipt-vouchers/:id/edit', component: ReceiptVoucherFormComponent },
      { path: 'accounting/check-books', component: CheckBooksListComponent },
      { path: 'accounting/check-books/new', component: CheckBookFormComponent },
      { path: 'accounting/check-books/:id/edit', component: CheckBookFormComponent },
      { path: 'accounting/issued-checks', component: IssuedChecksListComponent },
      { path: 'accounting/issued-checks/new', component: IssuedCheckFormComponent },
      { path: 'accounting/issued-checks/:id/edit', component: IssuedCheckFormComponent },
      { path: 'accounting/reports/general-ledger', component: GeneralLedgerComponent },
      { path: 'accounting/reports/trial-balance', component: TrialBalanceComponent },
      { path: 'banks/banks', component: BanksListComponent },
      { path: 'banks/banks/new', component: BankFormComponent },
      { path: 'banks/banks/:id/edit', component: BankFormComponent },
      { path: 'banks/accounts', component: BankAccountsListComponent },
      { path: 'banks/accounts/new', component: BankAccountFormComponent },
      { path: 'banks/accounts/:id/edit', component: BankAccountFormComponent },
      { path: 'banks/check-books', component: CheckBooksListComponent },
      { path: 'banks/check-books/new', component: CheckBookFormComponent },
      { path: 'banks/check-books/:id/edit', component: CheckBookFormComponent },
    ],
  },
];
