export const documentPrintEn = {
  'documentPrint.printPdf': 'Print / PDF',
  'documentPrint.generatedAt': 'Printed at',
  'documentPrint.footer': 'Document generated by Kayian ERP',
  'documentPrint.saveHint': 'Choose “Save as PDF” in the print dialog',
} as const;
