import { Component, inject, OnInit, signal } from '@angular/core';
import { FormArray, FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ProductLookup } from '../../../../core/api/models/product.models';
import { SaveStockAdjustmentRequest, StockAdjustmentDetail, StockAdjustmentStatus } from '../../../../core/api/models/stock-adjustment.models';
import { TakingAvailableForAdjustment } from '../../../../core/api/models/stock-taking.models';
import { Store } from '../../../../core/api/models/store.models';
import { extractApiErrorMessage } from '../../../../core/api/utils/api-response.util';
import { TranslatePipe } from '../../../../core/pipes/translate.pipe';
import { LanguageService } from '../../../../core/services/language.service';
import { ProductsService } from '../../../../core/services/products.service';
import { StockAdjustmentsService } from '../../../../core/services/stock-adjustments.service';
import { StockTakingsService } from '../../../../core/services/stock-takings.service';
import { StoresService } from '../../../../core/services/stores.service';
@Component({selector:'app-stock-adjustment-form',imports:[ReactiveFormsModule,RouterLink,TranslatePipe],templateUrl:'./stock-adjustment-form.component.html',styleUrl:'./stock-adjustment-form.component.scss'})
export class StockAdjustmentFormComponent implements OnInit{
 private route=inject(ActivatedRoute);private router=inject(Router);private service=inject(StockAdjustmentsService);private takings=inject(StockTakingsService);private storesService=inject(StoresService);private productsService=inject(ProductsService);private language=inject(LanguageService);
 id=signal<number|null>(null);adjNo=signal('');loading=signal(false);saving=signal(false);errorMessage=signal('');readOnly=signal(false);stores=signal<Store[]>([]);products=signal<ProductLookup[]>([]);availableTakings=signal<TakingAvailableForAdjustment[]>([]);
 form=new FormGroup({takingId:new FormControl<number|null>(null),storeId:new FormControl<number|null>(null,Validators.required),adjDate:new FormControl(new Date().toISOString().slice(0,10),{nonNullable:true,validators:Validators.required}),notes:new FormControl('',{nonNullable:true}),details:new FormArray<FormGroup>([])});get details(){return this.form.controls.details}
 ngOnInit(){this.storesService.getAll().subscribe({next:x=>this.stores.set(x)});this.productsService.getAll().subscribe({next:x=>this.products.set(x)});this.takings.getAvailableForAdjustment().subscribe({next:x=>this.availableTakings.set(x)});const id=Number(this.route.snapshot.paramMap.get('id'));if(id){this.id.set(id);this.load(id)}}
 load(id:number){this.loading.set(true);this.service.getById(id).subscribe({next:x=>{this.adjNo.set(x.adjNo??'');this.form.patchValue({takingId:x.takingId??null,storeId:x.storeId,adjDate:this.date(x.adjDate),notes:x.notes??''});x.details?.forEach(d=>this.addLine(d));this.readOnly.set(x.statusId===StockAdjustmentStatus.Posted);if(this.readOnly())this.form.disable();this.loading.set(false)},error:e=>{this.loading.set(false);this.errorMessage.set(extractApiErrorMessage(e,this.language.translate('stockAdjustments.notFound')))}})}
 loadFromTaking(){const id=this.form.controls.takingId.value;if(!id)return;this.service.getItemsFromTaking(id).subscribe({next:x=>{this.details.clear();x.forEach(d=>this.addLine(d))},error:e=>this.errorMessage.set(extractApiErrorMessage(e,this.language.translate('stockAdjustments.loadItemsError')))})}
 addLine(x?:Partial<StockAdjustmentDetail>){const old=Number(x?.oldQty??0),adj=Number(x?.adjQty??(Number(x?.newQty??old)-old));const g=new FormGroup({itemId:new FormControl(x?.itemId??null,Validators.required),unitId:new FormControl(x?.unitId??null,Validators.required),oldQty:new FormControl(old,{nonNullable:true}),adjQty:new FormControl(adj,{nonNullable:true}),newQty:new FormControl(Number(x?.newQty??old+adj),{nonNullable:true}),averageCost:new FormControl(x?.averageCost??0,{nonNullable:true}),totalValue:new FormControl(x?.totalValue??adj*Number(x?.averageCost??0),{nonNullable:true}),batchNumber:new FormControl(x?.batchNumber??'',{nonNullable:true}),expiryDate:new FormControl(this.date(x?.expiryDate),{nonNullable:true})});this.details.push(g);this.recalc(this.details.length-1)}
 recalc(i:number){const g=this.details.at(i),adj=Number(g.controls['adjQty'].value),old=Number(g.controls['oldQty'].value);g.controls['newQty'].setValue(old+adj,{emitEvent:false});g.controls['totalValue'].setValue(adj*Number(g.controls['averageCost'].value),{emitEvent:false})}removeLine(i:number){this.details.removeAt(i)}
 save(){if(this.form.invalid||!this.details.length){this.form.markAllAsTouched();return}this.saving.set(true);const v=this.form.getRawValue();const payload:SaveStockAdjustmentRequest={adjId:this.id()??undefined,takingId:v.takingId,storeId:v.storeId!,adjDate:v.adjDate,notes:v.notes||null,details:this.details.controls.map(ctrl=>({itemId:Number(ctrl.controls['itemId'].value),unitId:Number(ctrl.controls['unitId'].value),oldQty:Number(ctrl.controls['oldQty'].value),adjQty:Number(ctrl.controls['adjQty'].value),newQty:Number(ctrl.controls['newQty'].value),averageCost:Number(ctrl.controls['averageCost'].value),totalValue:Number(ctrl.controls['totalValue'].value),batchNumber:String(ctrl.controls['batchNumber'].value||'')||null,expiryDate:String(ctrl.controls['expiryDate'].value||'')||null}))};this.service.save(payload).subscribe({next:()=>void this.router.navigate(['/demo1/inventory/stock-adjustments'],{state:{successMessage:this.language.translate('stockAdjustments.saveSuccess')}}),error:e=>{this.saving.set(false);this.errorMessage.set(extractApiErrorMessage(e,this.language.translate('stockAdjustments.saveError')))}})}
 private date(x?:string|null){return x?x.slice(0,10):''}
}
